updated

diff --git a/checkupdate b/checkupdate
--- a/checkupdate
+++ b/checkupdate
@@ -10,14 +10,12 @@ print_progress() {
 }
 
 # default getver
-getver() {
+getver_default() {
 	fetch \
 	| grep -Eo $filename[_-][0-9a-z.]+.tar.[bgx]z2? \
 	| sed "s/$filename[-_]//;s/\.tar.*//" \
-	| grep -Evi '(alpha|beta|rc|pre)' \
 	| grep [[:digit:]] \
-	| sort -V \
-	| uniq
+	| $grepexclude
 }
 
 # per-type getver
@@ -26,19 +24,15 @@ getver_github() {
 	| grep archive \
 	| grep -Eo '(v?|"$filename"-)'[0-9a-z.]+\.tar\.gz \
 	| sed "s/\.tar\.gz//;s/^v//;s/^$filename-//" \
-	| grep -Evi '(alpha|beta|rc|example|pre|doc*|dev|start|cpp)' \
-	| sort -V \
-	| uniq
+	| $grepexclude
 }
 
 getver_ruby() {
 	fetch \
 	| grep -Eo $filename[_-][0-9a-z.]+.gem \
 	| sed "s/$filename[-_]//;s/\.gem//" \
-	| grep -Evi '(alpha|beta|rc|pre)' \
 	| grep [[:digit:]] \
-	| sort -V \
-	| uniq
+	| $grepexclude
 }
 
 getver_gnome() {
@@ -47,9 +41,14 @@ getver_gnome() {
 	| grep -Eo $filename-[0-9.]+.tar.[bgx]z2? \
 	| sed "s/$filename-//;s/\.tar.*//" \
 	| grep -Ew "^[0-9]+\.[0-9]*[02468]\.*" \
-	| grep -Ev "*.[89][0-9].*" \
-	| sort -V \
-	| uniq
+	| grep -Ev "*.[89][0-9].*"
+}
+
+getver_gnome2() {
+	fetch \
+	| tr ' ' '\n' \
+	| grep -Eo $filename-[0-9.]+.tar.[bgx]z2? \
+	| sed "s/$filename-//;s/\.tar.*//"
 }
 
 getver_xfce4() {	
@@ -59,7 +58,7 @@ getver_xfce4() {
 	| sort -V \
 	| uniq \
 	| tail -n1)	
-	getver
+	getver_default
 }
 
 getver_aur() {
@@ -78,6 +77,7 @@ fetch() {
 
 run_check() {
 	checkver_cmd=${1}
+	pname=${ppath#*/}
 	
 	if [ "$VERBOSE" = 1 ]; then
 		echo "file     : $file"
@@ -85,27 +85,25 @@ run_check() {
 		echo "version  : $version"
 		echo "url      : $url"
 		echo "cmd      : $checkver_cmd"
-		$checkver_cmd | tail -n10
-		return
+		$checkver_cmd | sort -V | uniq | tail -n10
 	else
 		print_progress "Checking '$ppath'"
-		upver=$($checkver_cmd | tail -n1)
+		upver=$($checkver_cmd | sort -V | uniq | tail -n1)
 		echo -ne "\033[0K"
-	fi
-	
-	upver=${upver:-404}
-	
-	if [ "$upver" = "404" ]; then
-		echo -e " $ppath: $version => ${RED}404${CRESET}"
-		[ "$OUT" = 1 ] && echo "$ppath $version => 404" >> error
-	elif [ "$version" != "$upver" ]; then
-		echo -e " $ppath: $version => ${YELLOW}$upver${CRESET}"
-		[ "$OUT" = 1 ] && echo "$ppath $version => $upver" >> outdate
-		if [ "$UPDATE" = 1 ]; then
-			sed "s/^version=.*/version=$upver/" -i $ppath/spkgbuild
-			pushd $ppath
-				fakeroot pkgbuild -m && sudo pkgbuild -u
-			popd
+
+		upver=${upver:-404}
+		
+		touch error outdate
+		
+		sed "\,^$pname ,d" -i error
+		sed "\,^$pname ,d" -i outdate
+
+		if [ "$upver" = "404" ]; then
+			echo -e " $ppath: $version => ${RED}404${CRESET}"
+			echo "$pname $version" >> error
+		elif [ "$version" != "$upver" ]; then
+			echo -e " $ppath: $version => ${YELLOW}$upver${CRESET}"
+			echo "$pname $upver" >> outdate
 		fi
 	fi
 }
@@ -143,10 +141,12 @@ check() {
 	fi
 	
 	# ignore
-	if [ -f ignoreupdate ] && grep -qx $ppath ignoreupdate; then
-		echo -e " $ppath: $version => ${GREEN}SKIP${CRESET}"
-		return
-	fi
+	[ -f ignoreupdate ] && {
+		if grep -x $ppath ignoreupdate >/dev/null; then
+			echo -e " $ppath: $version => ${GREEN}SKIP${CRESET}"
+			return
+		fi
+	}
 
 	if [ -z "$source" ]; then
 		echo -e " $ppath: $version => ${GREEN}SKIP${CRESET}"
@@ -155,8 +155,10 @@ check() {
 	
 	file=$(basename $(echo $source | awk '{print $1}'))
 	ext=$(echo $FILE | sed 's/.*\(\.t.*\).*/\1/')
-	filename=$(basename $file)
-	filename=${filename%-*}
+	#filename=$(basename $file)
+	filename=$(echo $file | sed "s/[-_]$version.*//")
+	#filename=${filename/-/_}
+	#filename=${filename%_*}
 
 	if echo $source | awk '{print $1}' | grep -q "::"; then
 		url=$(echo $source | awk '{print $1}' | awk -F '::' '{print $2}')
@@ -167,10 +169,12 @@ check() {
 
 	alter_per_url
 
-	[ -f $ppath/update ] && . $ppath/update
+	[ "$NOOVERRIDE" ] || {
+		[ -f $ppath/update ] && . $ppath/update
+	}
 
-	if [ "$(type -t getver_${name})" = "function" ]; then
-		run_check getver_${name}
+	if [ "$(type -t port_getver)" = "function" ]; then
+		run_check port_getver
 	else
 		case $url in
 			*github.com*|*gitlab.com*)
@@ -184,40 +188,93 @@ check() {
 			*kde.org/stable/plasma*|*kde.org/stable/frameworks*|*kde.org/stable/applications*)
 				;;
 			*)
-				run_check getver;;
+				run_check getver_default;;
 		esac
 	fi
 	
-	unset name version source
+	unset name version source port_getver url
 }
 
 parseopt() {
 	while [ $1 ]; do
 		case $1 in
-			-o) OUT=1;;
+			-r) while [ $2 ]; do
+					case $2 in
+						-*) break;;
+						*) REPO="$REPO $2"
+					esac
+					shift
+				done;;
+			-n) NOOVERRIDE=1;;
 			-v) VERBOSE=1;;
-			-u) UPDATE=1;;
-			 *) PKG+=($1);;
+			-h) print_help; exit 0;;
+			 *) PKG="$PKG $1";;
 		esac
 		shift
 	done
 }
 
+print_help() {
+	cat << EOF
+Script to check port's upstream update
+
+Usage:
+  ./$(basename $0) [ options ] [ <pkg1> <pkg2> <pkgN> ]
+  
+Options:
+  -r <repo>     check for certain repo
+  -n            dont use update file overrride
+  -v            print port's details
+  -h            show this help message
+      
+EOF
+}
+
 main() {
 	parseopt $@
 	
-	[ "$OUT" = 1 ] && rm -f outdate error
-	
-	if [ ${#PKG[@]} -gt 0 ]; then
-		for p in ${PKG[@]}; do
-			check $(find . -maxdepth 2 -mindepth 2 -name $p -printf "%P\n" | head -n1)
+	if [ "$exclude" ]; then
+		grepexclude="grep -i -v"
+		for i in $exclude; do
+			grepexclude="$grepexclude -e $i"
 		done
 	else
-		for d in ports/*/spkgbuild; do
-			check $(dirname $d)
+		grepexclude=cat
+	fi
+	
+	if [ "$REPO" ]; then
+		for repo in $REPO; do
+			if [ -d "$repo" ]; then
+				for d in $repo/*/spkgbuild; do
+					check $(dirname $d)
+				done
+			else
+				echo "Repo not exist: $repo"
+			fi
+		done
+	elif [ "$PKG" ]; then
+		for pkg in $PKG; do
+			found=0
+			for repo in $PORTREPO; do
+				if [ -f $repo/$pkg/spkgbuild ]; then
+					check $repo/$pkg
+					found=1
+					break
+				fi
+			done
+			[ "$found" = 0 ] && echo "Port not found: $pkg"
+		done
+	else
+		for repo in $PORTREPO; do
+			for pkg in $repo/*/spkgbuild; do
+				check $(dirname $pkg)
+			done
 		done
 	fi
 }
+
+PORTREPO="ports"
+exclude="alpha beta doc rc migration example pre dev start cpp data"
 
 main $@
 
